# -------- SUPABASE DATABASE --------
#spring.datasource.url=jdbc:postgresql://db.awsrkyyohuubpaazclrp.supabase.co:5432/postgres?sslmode=require
spring.datasource.url= https://awsrkyyohuubpaazclrp.supabase.co

spring.datasource.username=postgres
spring.datasource.password=2b073r1k8RZ7ohM2

# -------- JPA --------
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# -------- POOL (IMPORTANT) --------
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=30000

# -------- SERVER --------
server.port=8080