# ===============================
# DATASOURCE
# ===============================
spring.datasource.url=jdbc:postgresql://ep-red-term-adopqca0-pooler.c-2.us-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Zzn7TJRXx3Ac

# ===============================
# HIKARI (NEON OPTIMAL)
# ===============================
spring.datasource.hikari.maximumPoolSize=5
spring.datasource.hikari.minimumIdle=1
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.idleTimeout=300000
spring.datasource.hikari.maxLifetime=600000

# Neon specific fixes
spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require
spring.datasource.hikari.data-source-properties.prepareThreshold=0

# VERY IMPORTANT for Neon cold start
spring.datasource.hikari.initializationFailTimeout=0

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# performance
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.open-in-view=false