# -------- SUPABASE DATABASE --------
# MARCHE EN LOCAL
#spring.datasource.url=jdbc:postgresql://db.awsrkyyohuubpaazclrp.supabase.co:5432/postgres?sslmode=require
#spring.datasource.username=postgres
#spring.datasource.password=2b073r1k8RZ7ohM2

# POOLER OK
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.awsrkyyohuubpaazclrp
spring.datasource.password=2b073r1k8RZ7ohM2

# ------PORT---------
server.port=8080

# -------- JPA --------
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# -------- POOL (IMPORTANT) --------
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.data-source-properties.cachePrepStmts=false
spring.datasource.hikari.data-source-properties.useServerPrepStmts=false

